# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprland-workspaces = {
    pname = "hyprland-workspaces";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "FieldofClay";
      repo = "hyprland-workspaces";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-GhUjvFMlgjTdgtV9ASW7IqE2dBktPyOlRwg6qM1r7vc=";
    };
  };
  joker = {
    pname = "joker";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "candid82";
      repo = "joker";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-Y7FaW3V80mXp3l87srTLyhF45MlNH7QUZ5hrTudPtDU=";
    };
  };
  kamp = {
    pname = "kamp";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "kyleisah";
      repo = "Klipper-Adaptive-Meshing-Purging";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-anBGjLtYlyrxeNVy1TEMcAGTVUFrGClLuoJZuo3xlDM=";
    };
  };
  kibana = {
    pname = "kibana";
    version = "7.17.22";
    src = dockerTools.pullImage {
      imageName = "library/kibana";
      imageDigest = "sha256:834864700792e3a228b6ddf9313f53cd1a156b435714c30677a67f47eca4eb2e";
      sha256 = "sha256-O5Q93OETWq9GtTkrWy+HgD+ZUsIeSUPPhXq4pS+z80M=";
      finalImageTag = "7.17.22";
    };
  };
  linux-rockchip = {
    pname = "linux-rockchip";
    version = "709c51c64e1652d4f8c87b1815db86f56d188268";
    src = fetchFromGitHub {
      owner = "armbian";
      repo = "linux-rockchip";
      rev = "709c51c64e1652d4f8c87b1815db86f56d188268";
      fetchSubmodules = false;
      sha256 = "sha256-YZdWNhLopRyaEBojqMLMYEMKV6V0HcFgFmDbRSbBhRo=";
    };
    date = "2024-07-10";
  };
  live555 = {
    pname = "live555";
    version = "2c92a57ca04b83b2038ab2ab701d05a54be06a85";
    src = fetchFromGitHub {
      owner = "rgaufman";
      repo = "live555";
      rev = "2c92a57ca04b83b2038ab2ab701d05a54be06a85";
      fetchSubmodules = false;
      sha256 = "sha256-lfw5Ycm0jGAkSrh5So+hhtLlTnC9/cj8GfoMDPeCGSo=";
    };
    date = "2023-06-15";
  };
  pin-github-action = {
    pname = "pin-github-action";
    version = "v1.9.1";
    src = fetchFromGitHub {
      owner = "mheap";
      repo = "pin-github-action";
      rev = "v1.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-FBNdK+d1gXvC7uxARZrM7RHdwiPX/Vi1bp84R78t6wI=";
    };
  };
  sf-mono-nerd-font = {
    pname = "sf-mono-nerd-font";
    version = "v18.0d1e1.0";
    src = fetchFromGitHub {
      owner = "epk";
      repo = "SF-Mono-Nerd-Font";
      rev = "v18.0d1e1.0";
      fetchSubmodules = false;
      sha256 = "sha256-f5A/vTKCUxdMhCqv0/ikF46tRrx5yZfIkvfExb3/XEQ=";
    };
  };
  tfautomv = {
    pname = "tfautomv";
    version = "v0.6.2";
    src = fetchFromGitHub {
      owner = "busser";
      repo = "tfautomv";
      rev = "v0.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-qUeIbHJqxGkt2esMm4w6fM52ZE16jWnxugVXxqBh1Qc=";
    };
  };
  webrtc = {
    pname = "webrtc";
    version = "38e34668379ed705f3221160652165dc5d610444";
    src = fetchgit {
      url = "https://webrtc.googlesource.com/src";
      rev = "38e34668379ed705f3221160652165dc5d610444";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dMUEnaHr2vJ9/w9MKnnaXZVA1/blyt6QRYjans1pets=";
    };
    date = "2024-07-09";
  };
  webrtc-streamer = {
    pname = "webrtc-streamer";
    version = "v0.8.6";
    src = fetchFromGitHub {
      owner = "mpromonet";
      repo = "webrtc-streamer";
      rev = "v0.8.6";
      fetchSubmodules = true;
      sha256 = "sha256-TIeXHm7jvooCqyQa69mdNo7mQaEnEmuL5+mmkhOYWuk=";
    };
  };
}
