# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  joker = {
    pname = "joker";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "candid82";
      repo = "joker";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-aBZ0KlXWKAF70xFxc+WWXucLPnxyaCxu97IYkPuKcCA=";
    };
  };
  kamp = {
    pname = "kamp";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "kyleisah";
      repo = "Klipper-Adaptive-Meshing-Purging";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-anBGjLtYlyrxeNVy1TEMcAGTVUFrGClLuoJZuo3xlDM=";
    };
  };
  kibana = {
    pname = "kibana";
    version = "7.17.21";
    src = dockerTools.pullImage {
      imageName = "library/kibana";
      imageDigest = "sha256:00b785bb827cabf10be518ee03958fe233ba3a1f906ba18a6534dcc02f6c0da6";
      sha256 = "sha256-DPWkjukZzOvgecm09lA9y8a5PF4BckKs0BZH+Cv9OeU=";
      finalImageTag = "7.17.21";
    };
  };
  linux-rockchip = {
    pname = "linux-rockchip";
    version = "a51cda56da76e1b0a7ae2f31b91d6a51f5d74a69";
    src = fetchFromGitHub {
      owner = "armbian";
      repo = "linux-rockchip";
      rev = "a51cda56da76e1b0a7ae2f31b91d6a51f5d74a69";
      fetchSubmodules = false;
      sha256 = "sha256-/6TmH7KXwq6onMn12K7e54Pdt6ejzk7L9HY/+ZAqoqU=";
    };
    date = "2024-04-29";
  };
  pin-github-action = {
    pname = "pin-github-action";
    version = "v1.9.1";
    src = fetchFromGitHub {
      owner = "mheap";
      repo = "pin-github-action";
      rev = "v1.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-FBNdK+d1gXvC7uxARZrM7RHdwiPX/Vi1bp84R78t6wI=";
    };
  };
}
