[package]
name = "perf2ff"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-rustls = "0.27.5"
hyper-util = { version = "0.1", features = ["full"] }
rustls = "0.23.20"
rustls-pemfile = "2.2.0"
tokio = { version = "1", features = ["fs", "io-std", "macros"] }
tokio-rustls = "0.26.1"
tokio-util = "0.7.13"
url = "2.5.4"
